version: '2'

services:

  users-management:
    image: springboot-caching
    networks:
      - cache-network
    ports:
      - 8080:8080
    depends_on:
      - redis

  redis:
    image: redis:7.0.10
    networks:
      - cache-network
    ports:
    - 6379:6379

networks:
  cache-network:
    driver: bridge